-- pgAdmin Query Tool mein yeh chalao
SELECT * FROM customer LIMIT 10;
--Q1. What is the total revenue generated by Male vs. Female customers?

SELECT 
    "gender",
    COUNT(*) AS Total_Orders,
    SUM("order_value") AS Total_Revenue,
    ROUND(AVG("order_value")::numeric, 0) AS Avg_Order_Value
FROM customer
GROUP BY "gender"
ORDER BY Total_Revenue DESC;

--Q2. Which customers used a discount but still had a higher order value than the average?

SELECT 
    "customer_id",
    "order_value",
    "discount_applied",
    "cuisine_type",
    "city"
FROM customer
WHERE "discount_applied" = 'Yes'
AND "order_value" > (SELECT AVG("order_value") FROM customer)
ORDER BY "order_value" DESC
LIMIT 10;


--Q3. Which are the top 5 cuisines with the highest average rating?

SELECT 
    "cuisine_type",
    COUNT(*) AS Total_Orders,
    ROUND(AVG("rating")::numeric, 2) AS Avg_Rating,
    ROUND(AVG("delivery_time_min")::numeric, 1) AS Avg_Delivery_Time
FROM customer
GROUP BY "cuisine_type"
ORDER BY Avg_Rating DESC
LIMIT 5;

--Q4. Compare average Order Value between customers who used Promo Code vs. those who did not.

SELECT 
    "Promo_Code_Used",
    COUNT(*) AS Total_Orders,
    ROUND(AVG("Order_Value")::numeric, 0) AS Avg_Order_Value,
    SUM("Order_Value") AS Total_Revenue,
    ROUND(AVG("Rating")::numeric, 2) AS Avg_Rating
FROM customer
GROUP BY "Promo_Code_Used"
ORDER BY Avg_Order_Value DESC;

--Q5. Do Repeat Customers spend more? Compare avg spend and total revenue between repeat and new customers.

SELECT 
    "Repeat_Customer",
    COUNT(*) AS Total_Customers,
    ROUND(AVG("Order_Value")::numeric, 0) AS Avg_Order_Value,
    SUM("Order_Value") AS Total_Revenue,
    ROUND(AVG("Rating")::numeric, 2) AS Avg_Rating,
    ROUND(AVG("Delivery_Time_Min")::numeric, 1) AS Avg_Delivery_Time
FROM customer
GROUP BY "Repeat_Customer"
ORDER BY Avg_Order_Value DESC;

--Q6. Which cities have the highest percentage of repeat customers?

SELECT 
    City,
    COUNT(*) AS Total_Customers,
    SUM(CASE WHEN "Repeat_Customer" = 'Yes' THEN 1 ELSE 0 END) AS Repeat_Count,
    ROUND(
        SUM(CASE WHEN "Repeat_Customer" = 'Yes' THEN 1 ELSE 0 END) * 100.0 / COUNT(*), 1
    ) AS Repeat_Percentage
FROM customer
GROUP BY City
ORDER BY Repeat_Percentage DESC;

--Q7. Segment customers into High, Medium, Low based on their Order Value and show repeat rate of each.

SELECT 
    segment,
    COUNT(*) AS Total_Customers,
    ROUND(AVG("Order_Value")::numeric, 0) AS Avg_Order_Value,
    SUM(CASE WHEN "Repeat_Customer" = 'Yes' THEN 1 ELSE 0 END) AS Repeat_Count,
    ROUND(
        SUM(CASE WHEN "Repeat_Customer" = 'Yes' THEN 1 ELSE 0 END) * 100.0 / COUNT(*), 1
    ) AS Repeat_Pct
FROM (
    SELECT *,
        CASE 
            WHEN "Order_Value" >= 1605 THEN 'High Value'
            WHEN "Order_Value" >= 900  THEN 'Medium Value'
            ELSE 'Low Value'
        END AS segment
    FROM customer
) AS segmented
GROUP BY segment
ORDER BY Avg_Order_Value DESC;


--Q8. Discount ka Repeat Customer pe Effect?

SELECT 
    "discount_applied",
    COUNT(*) AS Total_Orders,
    ROUND(AVG("order_value")::numeric, 0) AS Avg_Order_Value,
    ROUND(AVG("rating")::numeric, 2) AS Avg_Rating,
    SUM(CASE WHEN "repeat_customer" = 'Yes' THEN 1 ELSE 0 END) AS Repeat_Customers,
    ROUND(
        SUM(CASE WHEN "repeat_customer" = 'Yes' THEN 1 ELSE 0 END) * 100.0 / COUNT(*), 1
    ) AS Repeat_Pct
FROM customer
GROUP BY "discount_applied"
ORDER BY Repeat_Pct DESC;


--Q9. What are the top 3 most ordered cuisines within each city?

SELECT 
    city,
    "cuisine_type",
    Total_Orders
FROM (
    SELECT 
        city,
        "cuisine_type",
        COUNT(*) AS Total_Orders,
        RANK() OVER (
            PARTITION BY city 
            ORDER BY COUNT(*) DESC
        ) AS rnk
    FROM customer
    GROUP BY city, "cuisine_type"
) AS ranked
WHERE rnk <= 3
ORDER BY city, rnk;

